Rearrange code to allow automatic cleanup of archive callbacks

diff --git a/functions/mkarch b/functions/mkarch
--- a/functions/mkarch
+++ b/functions/mkarch
@@ -2,196 +2,6 @@
 
 function _run_mkarch ()
 {
-	####################### OPTIONS #######################
-	emulate -L zsh
-	setopt extended_glob warn_create_global typeset_silent \
-		no_short_loops rc_quotes no_auto_pushd \
-		pipe_fail
-	########################################################
-
-
-	###################### VARIABLES #######################
-	local -A archs=()
-	local -U files=()
-
-	local PRINT_SIZE
-	local PRINT_TIME
-	local NAME
-	local EXTENSION
-	local ARCHIVE_NAME
-	########################################################
-
-
-	###################### FUNCTIONS  #######################
-	# (explicit cleanup in function mkarch)
-	local mkarch-gen_archive_name ()
-	{
-		ARCHIVE_NAME="$NAME"
-		# if output file exists, generate a random name
-		if [[ -f "${ARCHIVE_NAME}.${EXTENSION}" ]]; then
-			ARCHIVE_NAME=$(mktemp "${ARCHIVE_NAME}_XXX") && rm "$ARCHIVE_NAME" || return 1
-		fi
-
-		ARCHIVE_NAME="${ARCHIVE_NAME}.${EXTENSION}"
-		if [[ -f "$ARCHIVE_NAME" ]]; then
-			print -u2 "File '$ARCHIVE_NAME' already exists. Aborting"
-			return 1
-		fi
-	}
-
-	local mkarch-mk_tar_plain_archive ()
-	{
-		if [[ -n $PRINT_SIZE ]]; then
-			tar -cv --to-stdout "${files[@]}" 2>/dev/null | wc -c | numfmt --round=nearest --to=si --suffix=B --format="$EXTENSION archive size: %.2f" || { print -u2 "ERROR: $EXTENSION"; return 1 }
-		else
-			tar -cv -f "$ARCHIVE_NAME" "${files[@]}" > /dev/null 2>&1 && print "Output $EXTENSION archive to $ARCHIVE_NAME" || { print -u2 "ERROR: $EXTENSION"; return 1 }
-		fi
-	}
-
-	local mkarch-mk_tar_archive ()
-	{
-		if [[ -n $PRINT_SIZE ]]; then
-			tar -I "$COMPRESS_COMMAND" -cv --to-stdout "${files[@]}" 2>/dev/null | wc -c | numfmt --round=nearest --to=si --suffix=B --format="$EXTENSION archive size: %.2f" || { print -u2 "ERROR: $EXTENSION"; return 1 }
-		else
-			tar -I "$COMPRESS_COMMAND" -cv -f "$ARCHIVE_NAME" "${files[@]}" > /dev/null 2>&1 && print "Output $EXTENSION archive to $ARCHIVE_NAME" || { print -u2 "ERROR: $EXTENSION"; return 1 }
-		fi
-	}
-
-	local mkarch-mk_tar_bz2 ()
-	{
-		local COMPRESS_COMMAND='bzip2'
-		if command -v lbzip2 > /dev/null; then
-			COMPRESS_COMMAND='lbzip2'
-		fi
-
-		mkarch-mk_tar_archive
-	}
-
-	local mkarch-mk_tar_gz ()
-	{
-		local COMPRESS_COMMAND='gzip'
-		if command -v pigz > /dev/null; then
-			COMPRESS_COMMAND='pigz'
-		fi
-
-		mkarch-mk_tar_archive
-	}
-
-	local mkarch-mk_tar_xz ()
-	{
-		local COMPRESS_COMMAND='xz -T0'
-		if command -v pixz > /dev/null; then
-			COMPRESS_COMMAND='pixz'
-		fi
-
-		mkarch-mk_tar_archive
-	}
-
-	local mkarch-mk_tar_zst ()
-	{
-		local COMPRESS_COMMAND='zstd -T0'
-
-		mkarch-mk_tar_archive
-	}
-
-	local mkarch-mk_tar_lz4 ()
-	{
-		local COMPRESS_COMMAND='lz4'
-
-		mkarch-mk_tar_archive
-	}
-
-	local mkarch-mk_tar_lrz ()
-	{
-		# workaround for not working 'tar -I "lrzip"...' (fail decompression)
-		local tar_name=$(basename --suffix=.lrz "$ARCHIVE_NAME")
-		tar -cv -f "$tar_name" "${files[@]}" > /dev/null 2>&1 || { print -u2 "ERROR: $EXTENSION"; return 1 }
-
-		if [[ -n $PRINT_SIZE ]]; then
-			lrzip -D -q $tar_name --outfile - 2>&1  | wc -c | numfmt --round=nearest --to=si --suffix=B --format="$EXTENSION archive size: %.2f" || { print -u2 "ERROR: $EXTENSION"; return 1 }
-		else
-			lrzip -D -q $tar_name --outfile "$ARCHIVE_NAME" > /dev/null 2>&1 && print "Output $EXTENSION archive to $ARCHIVE_NAME" || { print -u2 "ERROR: $EXTENSION"; return 1 }
-		fi
-	}
-
-	local mkarch-mk_tar_lzo ()
-	{
-		local COMPRESS_COMMAND='lzop'
-
-		mkarch-mk_tar_archive
-	}
-
-	local mkarch-mk_7z ()
-	{
-		if [[ -n $PRINT_SIZE ]]; then
-			local tmp_arch=$(mktemp -t "dummy_XXX.z7") && rm "$tmp_arch" || return 1
-			7z a "$tmp_arch" "${files[@]}" > /dev/null 2>&1 || { print -u2 "ERROR: 7z"; return 1 }
-			wc -c "$tmp_arch" | cut -d' ' -f1 | numfmt --round=nearest --to=si --suffix=B --format="7z archive size: %.2f"
-			rm "$tmp_arch"
-		else
-			7z a "$ARCHIVE_NAME" "${files[@]}" > /dev/null 2>&1 && print "Output 7z archive to $ARCHIVE_NAME" || { print -u2 "ERROR: 7z"; return 1 }
-		fi
-	}
-
-	local mkarch-mk_rar ()
-	{
-		if [[ -n $PRINT_SIZE ]]; then
-			local tmp_arch=$(mktemp -t "dummy_XXX.rar") && rm "$tmp_arch" || return 1
-			rar a "$tmp_arch" "${files[@]}" > /dev/null 2>&1 || { print -u2 "ERROR: rar"; return 1 }
-			wc -c "$tmp_arch" | cut -d' ' -f1 | numfmt --round=nearest --to=si --suffix=B --format="rar archive size: %.2f"
-			rm "$tmp_arch"
-		else
-			rar a "$ARCHIVE_NAME" "${files[@]}" > /dev/null 2>&1 && print "Output rar archive to $ARCHIVE_NAME" || { print -u2 "ERROR: rar"; return 1 }
-		fi
-	}
-
-	local mkarch-mk_zip ()
-	{
-		if [[ -n $PRINT_SIZE ]]; then
-			zip -rq - "${files[@]}" | wc -c | numfmt --round=nearest --to=si --suffix=B --format="zip archive size: %.2f" || { print -u2 "ERROR: zip"; return 1 }
-		else
-			zip -rq "$ARCHIVE_NAME" "${files[@]}" && print "Output zip archive to $ARCHIVE_NAME" || { print -u2 "ERROR: zip"; return 1 }
-		fi
-	}
-	########################################################
-
-
-	####################### Generate map of available compression formats
-	if command -v tar > /dev/null; then
-		archs[tar]="mkarch-mk_tar_plain_archive"
-		if command -v bzip2 lbzip2 > /dev/null; then
-			archs[tar.bz2]="mkarch-mk_tar_bz2"
-		fi
-		if command -v gzip pigz > /dev/null; then
-			archs[tar.gz]="mkarch-mk_tar_gz"
-		fi
-		if command -v xz pixz > /dev/null; then
-			archs[tar.xz]="mkarch-mk_tar_xz"
-		fi
-		if command -v zstd > /dev/null; then
-			archs[tar.zst]="mkarch-mk_tar_zst"
-		fi
-		if command -v lz4 > /dev/null; then
-			archs[tar.lz4]="mkarch-mk_tar_lz4"
-		fi
-		if command -v lrzip > /dev/null; then
-			archs[tar.lrz]="mkarch-mk_tar_lrz"
-		fi
-		if command -v lzop > /dev/null; then
-			archs[tar.lzo]="mkarch-mk_tar_lzo"
-		fi
-	fi
-	if command -v 7z > /dev/null; then
-		archs[7z]="mkarch-mk_7z"
-	fi
-	if command -v rar > /dev/null; then
-		archs[rar]="mkarch-mk_rar"
-	fi
-	if command -v zip > /dev/null; then
-		archs[zip]="mkarch-mk_zip"
-	fi
-	#######################
-
 	####################### Generate usage info
 	local usage="Archive files and directories using a given compression format.
 Usage: mkarch <options> [format] [files...]
@@ -338,23 +148,192 @@ Usage: mkarch <options> [format] [files...]
 
 function mkarch ()
 {
+	####################### OPTIONS #######################
+	emulate -L zsh
+	setopt extended_glob warn_create_global typeset_silent \
+		no_short_loops rc_quotes no_auto_pushd \
+		pipe_fail
+	########################################################
+
+	###################### VARIABLES #######################
+	local -A archs=()
+	local -U files=()
+
+	local PRINT_SIZE
+	local PRINT_TIME
+	local NAME
+	local EXTENSION
+	local ARCHIVE_NAME
+	########################################################
+
+	###################### FUNCTIONS  #######################
+	# (needs explicit cleanup)
+	local mkarch-gen_archive_name ()
+	{
+		ARCHIVE_NAME="$NAME"
+		# if output file exists, generate a random name
+		if [[ -f "${ARCHIVE_NAME}.${EXTENSION}" ]]; then
+			ARCHIVE_NAME=$(mktemp "${ARCHIVE_NAME}_XXX") && rm "$ARCHIVE_NAME" || return 1
+		fi
+
+		ARCHIVE_NAME="${ARCHIVE_NAME}.${EXTENSION}"
+		if [[ -f "$ARCHIVE_NAME" ]]; then
+			print -u2 "File '$ARCHIVE_NAME' already exists. Aborting"
+			return 1
+		fi
+	}
+
+	local mkarch-mk_tar_archive ()
+	{
+		if [[ -n $PRINT_SIZE ]]; then
+			tar -I "$COMPRESS_COMMAND" -cv --to-stdout "${files[@]}" 2>/dev/null | wc -c | numfmt --round=nearest --to=si --suffix=B --format="$EXTENSION archive size: %.2f" || { print -u2 "ERROR: $EXTENSION"; return 1 }
+		else
+			tar -I "$COMPRESS_COMMAND" -cv -f "$ARCHIVE_NAME" "${files[@]}" > /dev/null 2>&1 && print "Output $EXTENSION archive to $ARCHIVE_NAME" || { print -u2 "ERROR: $EXTENSION"; return 1 }
+		fi
+	}
+	########################################################
+
+	####################### Generate map of available compression formats
+	if command -v tar > /dev/null; then
+		local mkarch-mk_tar_plain_archive ()
+		{
+			if [[ -n $PRINT_SIZE ]]; then
+				tar -cv --to-stdout "${files[@]}" 2>/dev/null | wc -c | numfmt --round=nearest --to=si --suffix=B --format="tar archive size: %.2f" || { print -u2 "ERROR: tar"; return 1 }
+			else
+				tar -cv -f "$ARCHIVE_NAME" "${files[@]}" > /dev/null 2>&1 && print "Output tar archive to $ARCHIVE_NAME" || { print -u2 "ERROR: tar"; return 1 }
+			fi
+		}
+		archs[tar]="mkarch-mk_tar_plain_archive"
+		if command -v bzip2 lbzip2 > /dev/null; then
+			local mkarch-mk_tar_bz2 ()
+			{
+				local COMPRESS_COMMAND='bzip2'
+				if command -v lbzip2 > /dev/null; then
+					COMPRESS_COMMAND='lbzip2'
+				fi
+
+				mkarch-mk_tar_archive
+			}
+			archs[tar.bz2]="mkarch-mk_tar_bz2"
+		fi
+		if command -v gzip pigz > /dev/null; then
+			local mkarch-mk_tar_gz ()
+			{
+				local COMPRESS_COMMAND='gzip'
+				if command -v pigz > /dev/null; then
+					COMPRESS_COMMAND='pigz'
+				fi
+
+				mkarch-mk_tar_archive
+			}
+			archs[tar.gz]="mkarch-mk_tar_gz"
+		fi
+		if command -v xz pixz > /dev/null; then
+			local mkarch-mk_tar_xz ()
+			{
+				local COMPRESS_COMMAND='xz -T0'
+				if command -v pixz > /dev/null; then
+					COMPRESS_COMMAND='pixz'
+				fi
+
+				mkarch-mk_tar_archive
+			}
+			archs[tar.xz]="mkarch-mk_tar_xz"
+		fi
+		if command -v zstd > /dev/null; then
+			local mkarch-mk_tar_zst ()
+			{
+				local COMPRESS_COMMAND='zstd -T0'
+
+				mkarch-mk_tar_archive
+			}
+			archs[tar.zst]="mkarch-mk_tar_zst"
+		fi
+		if command -v lz4 > /dev/null; then
+			local mkarch-mk_tar_lz4 ()
+			{
+				local COMPRESS_COMMAND='lz4'
+
+				mkarch-mk_tar_archive
+			}
+			archs[tar.lz4]="mkarch-mk_tar_lz4"
+		fi
+		if command -v lrzip > /dev/null; then
+			local mkarch-mk_tar_lrz ()
+			{
+				# workaround for not working 'tar -I "lrzip"...' (fail decompression)
+				local tar_name=$(basename --suffix=.lrz "$ARCHIVE_NAME")
+				tar -cv -f "$tar_name" "${files[@]}" > /dev/null 2>&1 || { print -u2 "ERROR: tar.lrz"; return 1 }
+
+				if [[ -n $PRINT_SIZE ]]; then
+					lrzip -D -q $tar_name --outfile - 2>&1  | wc -c | numfmt --round=nearest --to=si --suffix=B --format="tar.lrz archive size: %.2f" || { print -u2 "ERROR: tar.lrz"; return 1 }
+				else
+					lrzip -D -q $tar_name --outfile "$ARCHIVE_NAME" > /dev/null 2>&1 && print "Output tar.lrz archive to $ARCHIVE_NAME" || { print -u2 "ERROR: tar.lrz"; return 1 }
+				fi
+			}
+			archs[tar.lrz]="mkarch-mk_tar_lrz"
+		fi
+		if command -v lzop > /dev/null; then
+			local mkarch-mk_tar_lzo ()
+			{
+				local COMPRESS_COMMAND='lzop'
+
+				mkarch-mk_tar_archive
+			}
+			archs[tar.lzo]="mkarch-mk_tar_lzo"
+		fi
+	fi
+	if command -v 7z > /dev/null; then
+		local mkarch-mk_7z ()
+		{
+			if [[ -n $PRINT_SIZE ]]; then
+				local tmp_arch=$(mktemp -t "dummy_XXX.z7") && rm "$tmp_arch" || return 1
+				7z a "$tmp_arch" "${files[@]}" > /dev/null 2>&1 || { print -u2 "ERROR: 7z"; return 1 }
+				wc -c "$tmp_arch" | cut -d' ' -f1 | numfmt --round=nearest --to=si --suffix=B --format="7z archive size: %.2f"
+				rm "$tmp_arch"
+			else
+				7z a "$ARCHIVE_NAME" "${files[@]}" > /dev/null 2>&1 && print "Output 7z archive to $ARCHIVE_NAME" || { print -u2 "ERROR: 7z"; return 1 }
+			fi
+		}
+		archs[7z]="mkarch-mk_7z"
+	fi
+	if command -v rar > /dev/null; then
+		local mkarch-mk_rar ()
+		{
+			if [[ -n $PRINT_SIZE ]]; then
+				local tmp_arch=$(mktemp -t "dummy_XXX.rar") && rm "$tmp_arch" || return 1
+				rar a "$tmp_arch" "${files[@]}" > /dev/null 2>&1 || { print -u2 "ERROR: rar"; return 1 }
+				wc -c "$tmp_arch" | cut -d' ' -f1 | numfmt --round=nearest --to=si --suffix=B --format="rar archive size: %.2f"
+				rm "$tmp_arch"
+			else
+				rar a "$ARCHIVE_NAME" "${files[@]}" > /dev/null 2>&1 && print "Output rar archive to $ARCHIVE_NAME" || { print -u2 "ERROR: rar"; return 1 }
+			fi
+		}
+		archs[rar]="mkarch-mk_rar"
+	fi
+	if command -v zip > /dev/null; then
+		local mkarch-mk_zip ()
+		{
+			if [[ -n $PRINT_SIZE ]]; then
+				zip -rq - "${files[@]}" | wc -c | numfmt --round=nearest --to=si --suffix=B --format="zip archive size: %.2f" || { print -u2 "ERROR: zip"; return 1 }
+			else
+				zip -rq "$ARCHIVE_NAME" "${files[@]}" && print "Output zip archive to $ARCHIVE_NAME" || { print -u2 "ERROR: zip"; return 1 }
+			fi
+		}
+		archs[zip]="mkarch-mk_zip"
+	fi
+	#######################
+
 	local ret
 	_run_mkarch $@ || ret=$?
 
-	# cleanup _run_mkarch local functions
+	# cleanup local functions
 	unfunction "mkarch-gen_archive_name"
-	unfunction "mkarch-mk_tar_plain_archive"
 	unfunction "mkarch-mk_tar_archive"
-	unfunction "mkarch-mk_tar_bz2"
-	unfunction "mkarch-mk_tar_gz"
-	unfunction "mkarch-mk_tar_xz"
-	unfunction "mkarch-mk_tar_zst"
-	unfunction "mkarch-mk_tar_lz4"
-	unfunction "mkarch-mk_tar_lrz"
-	unfunction "mkarch-mk_tar_lzo"
-	unfunction "mkarch-mk_7z"
-	unfunction "mkarch-mk_rar"
-	unfunction "mkarch-mk_zip"
+	local archs_func
+	for archs_func in ${(v)archs}; do
+		unfunction "$archs_func"
+	done
 
 	return $ret
 }
